"""empty message

Revision ID: e41f2aaf9466
Revises: 9525f32105df
Create Date: 2020-05-05 10:52:52.429033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41f2aaf9466'
down_revision = '9525f32105df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'image_file')
    # ### end Alembic commands ###
