"""empty message

Revision ID: f48c184539b5
Revises: e41f2aaf9466
Create Date: 2020-05-05 11:01:30.140644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48c184539b5'
down_revision = 'e41f2aaf9466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'image_file')
    # ### end Alembic commands ###
